#! /bin/sh

# exit immediately on error
set -e

psql -q -c "CREATE USER sessionauthuser SUPERUSER PASSWORD '123'"
echo "Created Postgres user 'sessionauthuser'"

psql -q -c "CREATE DATABASE sessionauthdb WITH OWNER sessionauthuser"
echo "Created Postgres database 'sessionauthdb'"

cp -n example.env .env
echo "Created .env with database URL"